title : Architect theme
description : Architect is the theme for Github pages.
show_downloads : false
google_analytics : 
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
